name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed


jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull 220103263/mid2:latest
    - name: Delete Old docker container
      run: sudo docker rm -f mid2-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name mid2-container 220103263/mid2
